param(
    [string]$TagName = "",
    [string]$ProjectPath = "",
    [string]$ChangelogPath = "",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptRoot

if ([string]::IsNullOrWhiteSpace($ProjectPath)) {
    $ProjectPath = Join-Path $repoRoot "src\WinAiUsageBar.App\WinAiUsageBar.App.csproj"
}

if ([string]::IsNullOrWhiteSpace($ChangelogPath)) {
    $ChangelogPath = Join-Path $repoRoot "CHANGELOG.md"
}

function Get-FirstTextValue {
    param(
        [Parameter(Mandatory = $true)]
        [object[]]$Values,
        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    $value = $Values |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        Select-Object -First 1

    if ([string]::IsNullOrWhiteSpace($value)) {
        throw "$Name was not found in $ProjectPath"
    }

    return [string]$value
}

function Get-VersionFromProject {
    [xml]$projectXml = Get-Content -LiteralPath $ProjectPath
    $propertyGroups = @($projectXml.Project.PropertyGroup)
    return Get-FirstTextValue -Values ($propertyGroups | ForEach-Object { $_.Version }) -Name "Version"
}

function Get-ChangelogSection {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content,
        [Parameter(Mandatory = $true)]
        [string]$Version
    )

    $escapedVersion = [regex]::Escape($Version)
    $match = [regex]::Match(
        $Content,
        "(?ms)^##\s+$escapedVersion\s+-\s+\d{4}-\d{2}-\d{2}\s*$\r?\n(?<body>.*?)(?=^##\s+|\z)")

    if (-not $match.Success) {
        throw "CHANGELOG release section was not found for version $Version."
    }

    return $match.Groups["body"].Value.Trim()
}

function Get-PreviousChangelogVersion {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content,
        [Parameter(Mandatory = $true)]
        [string]$Version
    )

    $matches = [regex]::Matches($Content, "(?m)^##\s+([0-9]+\.[0-9]+\.[0-9]+)\s+-\s+\d{4}-\d{2}-\d{2}\s*$")
    for ($index = 0; $index -lt $matches.Count; $index++) {
        if ($matches[$index].Groups[1].Value -eq $Version -and $index + 1 -lt $matches.Count) {
            return $matches[$index + 1].Groups[1].Value
        }
    }

    return ""
}

function Assert-EnglishReleaseText {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Text
    )

    foreach ($character in $Text.ToCharArray()) {
        $codePoint = [int][char]$character
        $isJapaneseOrCjk =
            ($codePoint -ge 0x3040 -and $codePoint -le 0x309F) -or
            ($codePoint -ge 0x30A0 -and $codePoint -le 0x30FF) -or
            ($codePoint -ge 0x4E00 -and $codePoint -le 0x9FFF)

        if ($isJapaneseOrCjk) {
            throw "Release notes must be written in English. Japanese/CJK characters were found in the current changelog section."
        }
    }
}

if (-not (Test-Path -LiteralPath $ProjectPath -PathType Leaf)) {
    throw "Project file was not found: $ProjectPath"
}

if (-not (Test-Path -LiteralPath $ChangelogPath -PathType Leaf)) {
    throw "CHANGELOG was not found: $ChangelogPath"
}

$version = Get-VersionFromProject
$expectedTag = "v$version"
if ([string]::IsNullOrWhiteSpace($TagName)) {
    $TagName = $expectedTag
}
elseif ($TagName -ne $expectedTag) {
    throw "Release tag ($TagName) must match app version tag ($expectedTag)."
}

$changelog = Get-Content -LiteralPath $ChangelogPath -Raw
$section = Get-ChangelogSection -Content $changelog -Version $version
Assert-EnglishReleaseText -Text $section

$previousVersion = Get-PreviousChangelogVersion -Content $changelog -Version $version
$fullChangelogUrl = if ([string]::IsNullOrWhiteSpace($previousVersion)) {
    "https://github.com/lingmulongtai/WinAI-Usage-Bar/releases/tag/$TagName"
}
else {
    "https://github.com/lingmulongtai/WinAI-Usage-Bar/compare/v$previousVersion...$TagName"
}

$notes = @"
## Changes

WinAI Usage Bar $TagName includes the following changes from ``CHANGELOG.md``.

$section

## Verification

- Release workflow verifies metadata, installer script syntax, restore, build, tests, publish, smoke test, packaging, installer build, and release readiness.
- Release assets are generated by GitHub Actions and attached to the draft release before publishing.

## Assets

- ``WinAIUsageBar-$version-win-x64.zip``
- ``WinAIUsageBar-$version-win-x64.zip.sha256``
- ``WinAIUsageBar-$version-setup.exe``
- ``WinAIUsageBar-$version-setup.exe.sha256``

## Notes

This is still an MVP intended for personal dogfooding. The binaries are not code-signed yet, so Windows SmartScreen or installer warnings may appear.

**Full Changelog**: $fullChangelogUrl
"@

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    Write-Output $notes.TrimEnd()
}
else {
    $outputDirectory = Split-Path -Parent $OutputPath
    if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
        New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
    }

    $notes.TrimEnd() | Set-Content -LiteralPath $OutputPath -Encoding utf8
    Write-Host "Release notes written to $OutputPath"
}
